"""Markdown report generator.

Assembles a grounded design report from deterministic outputs only. Includes an
explicit scientific-limitations section and labels the maturity level. No claim
here originates from an LLM; the optional AI layer may *rewrite* prose but must
be grounded against these same outputs.
"""
from __future__ import annotations

from typing import List, Optional

from . import __version__, CAUTION
from .designer import DesignResult
from .explainability import explain_all, improvement_suggestions
from .sanity import run_sanity


def lab_plan(result: DesignResult) -> List[str]:
    inp = result.inp
    plan = [
        "Solubility / clarity check of drug in the selected solvent (visual + optional UV).",
        "Prepare a small pilot batch by the selected process method.",
    ]
    if inp.family in ("niosome", "liposome", "transfersome", "ethosome", "bilosome", "proniosome"):
        plan.append("Hydration / reconstitution of the film; note dispersion appearance.")
    plan += [
        "Size + PDI by dynamic light scattering (DLS).",
        "Zeta potential in the intended dispersion medium.",
        "Encapsulation efficiency and drug loading (separation + assay).",
    ]
    if inp.design_goal in ("sustained_release", "oral_bilosome") or inp.family in (
            "solid_lipid_nanoparticle", "nanostructured_lipid_carrier", "polymeric_nanoparticle"):
        plan.append("In-vitro release profile (dialysis / Franz cell as appropriate).")
    plan.append("Short-term physical stability at 4 C and 25 C over 24-48 h (size/PDI/zeta drift).")
    if inp.route == "pulmonary":
        plan.append("Aerodynamic assessment (NGI/ACI) and post-nebulization integrity check.")
    if inp.route == "parenteral":
        plan.append("Sterility, endotoxin, osmolality, and injectability checks.")
    return plan


def build_markdown_report(result: DesignResult, include_batch: bool = True) -> str:
    inp = result.inp
    L: List[str] = []
    L.append(f"# NanoFormulationDesigner — Design Report")
    L.append(f"_Generated by nanoform v{__version__}. {CAUTION}_\n")

    L.append("## 1. Executive decision")
    L.append(f"- **Decision:** {result.executive_decision}")
    L.append(f"- **Design maturity:** {result.maturity_label}")
    L.append(f"- **NanoForm composite score:** {result.nanoform_score:.2f} / 1.00")
    L.append(f"- **Family / route / process:** {inp.family} / {inp.route} / {inp.process_method}")
    L.append(f"- **Drug:** {inp.drug} at {inp.drug_mol_percent:.1f} mol% of membrane; "
             f"solvent: {inp.solvent or 'n/a'}; carrier: {inp.carrier or 'n/a'}\n")

    L.append("## 2. CQA decision table")
    L.append("| CQA | Estimate | Score | Category |")
    L.append("|---|---|---|---|")
    for c in result.cqas:
        cat = "composite" if c.key == "nanoform_score" else "descriptor-driven"
        L.append(f"| {c.label} | {c.estimate} | {c.score:.2f} | {cat} |")
    L.append("")

    L.append("## 3. Descriptors")
    L.append("| Descriptor | Value |")
    L.append("|---|---|")
    for k, v in result.descriptors.values.items():
        L.append(f"| {k} | {_fmt(v)} |")
    L.append("")

    if include_batch:
        L.append("## 4. Batch mass table")
        L.append("| Component | Role | mol% | umol | MW | mg |")
        L.append("|---|---|---|---|---|---|")
        for r in result.batch_table:
            L.append(f"| {r['component']} | {r['role']} | {r['mol_percent']} | "
                     f"{r['umol']} | {_fmt(r['MW'])} | {_fmt(r['mg'])} |")
        total_mg = sum(r["mg"] for r in result.batch_table if isinstance(r["mg"], (int, float)))
        L.append(f"\n_Total mass (resolved components): {total_mg:.2f} mg._\n")

    L.append("## 5. Explanation (drivers / risks / recommended change)")
    for e in explain_all(result):
        L.append(f"### {e.cqa_key}")
        if e.positive_drivers:
            L.append("- **Positive drivers:** " + "; ".join(e.positive_drivers))
        if e.risk_drivers:
            L.append("- **Risk drivers:** " + "; ".join(e.risk_drivers))
        L.append(f"- **Interpretation:** {e.interpretation}")
        L.append(f"- **Recommended change:** {e.recommended_change}")
    L.append("")

    L.append("## 6. Improvement suggestions")
    for s in improvement_suggestions(result):
        L.append(f"- {s}")
    L.append("")

    L.append("## 7. Sanity checks")
    for w in run_sanity(result):
        L.append(f"- **[{w.severity.upper()}]** {w.message}")
    L.append("")

    L.append("## 8. Suggested lab screening plan")
    for i, step in enumerate(lab_plan(result), 1):
        L.append(f"{i}. {step}")
    L.append("")

    L.append("## 9. Scientific limitations")
    L += _limitations(result)
    return "\n".join(L)


def _limitations(result: DesignResult) -> List[str]:
    out = [
        "- Outputs are **descriptor-driven decision-support estimates**, not validated predictions.",
        "- CQA scores are **heuristic** until trained/validated on internal experimental outcomes "
        "(current maturity is capped at DML-2).",
        "- Some constants (HSP, headgroup area, molar volume, some Tg) are **estimated**; confidence "
        "depends on database coverage.",
    ]
    if result.missing_values:
        out.append("- **Missing / unresolved values in this design:** " + "; ".join(result.missing_values))
    for n in result.descriptors.notes:
        out.append(f"- Note: {n}")
    out.append("- All candidates **require laboratory verification** before any decision.")
    return out


def _fmt(v):
    if v is None:
        return "—"
    if isinstance(v, float):
        return f"{v:.3f}"
    return str(v)


def save_report(text: str, path: str) -> str:
    with open(path, "w", encoding="utf-8") as f:
        f.write(text)
    return path
